language: python

- provider: script
    script: python scripts/compile.py
- provider: script
    script: python installer/installer.py

install:

script: python setup.py test

jobs:
  include:
    - python: 3.5
    - python: 3.6
