language: python
stages:
- setup

install:
  - pip install -r requirements.txt
  - pip install PyInstaller
  - pip install setuptools
  - pip install pytest
  - python setup.py install

os:
  - linux
  #- windows

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial

    #- os: windows
    #  script: python installer/installer.py

    - stage: setup
      script: python setup.py build sdist bdist

script: pytest


